//Jenkins file

pipeline {
    //agent any
    agent { docker { image 'maven:3.6.3} }
    ENVIRONMENT {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = $dockerHome/bin:$mavenHome/bin:"$PATH"
    stages {
        stage('Checkout') {
            steps {
                sh 'mvn --version'
                echo "Build"
                echo "$PATH"
                echo "BUILD_NUMBER = $env.BUILD_NUMBER"
            }
        }
        stage('Compile') {
            steps {
                sh "mvn clean compile"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test"
            }
        }
        stage('Integration Test') {
            steps {
                sh "mvn failsafe:integration-test failsafeverify"
            }   
        }
         stage('Package') {
            steps {
                sh "mvn packagge -DskipTests"
            }   
        }
        stage('Build Docker Image') {
            steps {
                //docker build -t dockerImageAddress:BUILDTAG
                script {
                    dockerImage = docker.build("dockerImageAdress;BUILDTAG")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'dockerHub') {
                        dockerImage.push();
                        dockerImage.push('latest');
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'I run always'
        }
        success {
            echo 'I run when you are sucessful'
        }
        failure {
            echo 'I run when you fail'
        }
    }
}   
        
